config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  unauthenticated do
    root 'pages#home'
  end 

  # Service Workers
  get '/manifest.json', to: 'service_workers/manifests#index'

  # Users
  devise_for :users, skip: [:registrations, :invitation]
  devise_scope :user do
    resource :users,
            only: [:edit, :update, :destroy],
            controller: 'devise/registrations',
            as: :user_registration do
      get 'cancel'
    end
  end

  devise_scope :user do
    get "/users/invitation/accept", to: "devise/invitations#edit",   as: 'accept_user_invitation'
    patch '/users/invitation', to: 'devise/invitations#update', as: 'user_invitation'
  end

  # Super Admin User
  authenticated :user, ->(u) { u.super_admin? } do
    # Sidekiq
    mount Sidekiq::Web => '/sidekiq'
    mount Flipper::UI.app(Flipper) => '/flipper'
    root 'manage/manage#dashboard', as: :manager_root

    devise_scope :user do
      get "/users/invitation/accept", to: "devise/invitations#edit",   as: 'manage_accept_user_invitation'
      get '/users/invitation/new', to: 'devise/invitations#new', as: 'manage_new_user_invitation'
      patch '/users/invitation', to: 'devise/invitations#update', as: 'manage_user_invitation'
      put "/users/invitation", to: "devise/invitations#update", as:  nil
    end

    # Manage
    namespace :manage do
      root 'manage#dashboard', as: :manager_root
      get '/ripples', to: 'manage#ripples', as: 'ripples'
      get '/releases', to: 'manage#releases', as: 'releases'
      get '/tags', to: 'manage#tags', as: 'tags'

      resources :ponds, param: :key do
        resources :ripples, param: :uuid
      end

      resources :tags, param: :name
      resources :stories, param: :uuid
      resources :orders, param: :uuid
      post '/orders/:uuid/send_message', to: 'orders#send_message', as: 'order_send_message'
      resources :bills
      resources :organizations, param: :name do 
        resources :releases do 
          resources :pond_batch_record, only: [:new, :create]
        end
        resources :tags, param: :name, only: [:index, :show]
      end
    end
  end

  # Admin User
  authenticated :user, ->(u) { u.admin? } do
    # Manage
    namespace :manage do
      resources :ponds, param: :key do
        resources :ripples, param: :uuid
      end

      resources :orders, param: :uuid
      resources :tags, param: :name
      resources :stories, param: :uuid
      resources :organizations, param: :name do 
        resources :releases
        resources :tags, param: :name, only: [:index, :show]
      end
    end
  end 

  # Pages
  get '/ripples', to: 'pages#ripples'
  get '/impact', to: 'pages#impact'
  get '/donate', to: 'pages#donate'
  get '/contribute', to: 'pages#contribute'
  get '/privacy', to: 'pages#privacy_policy'
  get '/terms', to: 'pages#terms'
  get '/thank-you', to: 'pages#thank_you'
  get '/explained', to: 'pages#explained'
  get '/gracehaven', to: 'pages#partner', as: 'partner'

  # Orders
  resources :orders, param: :uuid, only: %i[show new create]

  # Donations
  resources :donations, only: [:create]

  # Ponds and Ripples
  resources :ponds, param: :key, only: [:index, :show] do
    resources :ripples, param: :uuid, only: [:index, :show, :create, :new]
  end

  # Tags
  resources :tags, param: :name, only: [:index, :show, :new, :create]

  # Stories
  resources :stories, param: :uuid, only: [:new, :create]

  # Organizations
  resources :organizations, param: :name, only: [:index, :show] do 
    resources :releases, only: [:index, :show]
    resources :tags, param: :name, only: [:index, :show]
  end

  # Twilio Message Subscriptions
  post '/messagesubscriptions/sms', to: 'message_subscriptions#sms'

  # API Routes
  namespace :api do
    get '/_ping', to: 'health#ping'

    namespace :internal do
      resources :ponds, only: [:index, :show]
      resources :ripples, only: [:index, :show]
      resources :organizations, only: [:index, :show]
      resources :releases, only: [:index, :show]
      resources :tags, only: [:index, :show]
      resources :stories, only: [:index, :show]
      get '/impact', to: 'impact#show'
    end
  end
  

end

app/models/pond.rb
# frozen_string_literal: true

class Pond < ApplicationRecord
  extend FriendlyId
  include PondRippleConcern

  # Schema Information
  # Table name: Pond
  #
  # id                  :integer      not null, primary key
  # uuid                :string       not null, unique true
  # key                 :string       not null, unique true
  # release_id          :integer      not null,
  # postal_code         :string
  # region              :string
  # city                :string
  # country             :string
  # deleted_at          :datetime
  # created_at          :datetime     not null
  # updated_at          :datetime     not null

  # Model Callbacks
  after_initialize :initialize_uuid, :initialize_key
  before_create :convert_country_code
  before_save :uppercase_key

  # Validations
  validates :uuid, :key, presence: true, uniqueness: true
  validates :uuid, length: { is: 36 }
  validates :key, length: { is: 8 }
  validate :validate_key, :validate_uuid

  # Alias Attributes
  alias_attribute :state, :region
  alias_attribute :pond_key, :key

  # Associations
  has_many :ripples, dependent: :destroy
  belongs_to :release
  has_one :organization, through: :release

  # Scopes
  scope :inactive, -> { where(['updated_at < ?', Time.zone.now - 45.days]) }
  scope :active, -> { where.not(['updated_at < ?', Time.zone.now - 45.days]) }

  # Gem Configurations
  has_paper_trail
  acts_as_paranoid
  friendly_id :key, use: :slugged

  #
  # Public Instance Method
  #
  # Returns a url for it self
  def url
    ::Routes.pond_url(self)
  end

  #
  # Public Instance Method
  #
  # Returns a new ripple url for it self
  def new_ripple_url
    ::Routes.new_pond_ripple_url(self)
  end

  #
  # Public Instance Method
  #
  # Returns if a ripple is active or not
  def create_qr_code
    qrcode = RQRCode::QRCode.new(new_ripple_url)

    qrcode.as_png(
      bit_depth: 1,
      border_modules: 4,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: '#1484ac',
      file: nil,
      fill: 'white',
      module_px_size: 6,
      resize_exactly_to: false,
      resize_gte_to: false,
      size: 300
    )
  end

  #
  # Public Instance Method
  #
  # Returns if a ripple is active or not
  def active?
    updated_at < Time.current - 45.days
  end

  #
  # Public Instance Method
  #
  # Returns an integer count of ripples
  def impact
    ripples.count
  end

  #
  # Public Instance Method
  #
  # Returns an integer count of international ripples
  def international_impact
    ripples.international.count
  end

  #
  # Public Instance Method
  #
  # Returns an integer count of domestic ripples
  def domestic_impact
    ripples.domestic.count
  end

  #
  # Public Instance Method
  #
  # Returns the ponds last ripple
  def last_ripple
    ripples.last
  end

  #
  # Public Instance Method
  #
  # Returns when the time since ponds last ripple was recorded and now
  # Example: '3 weeks ago'
  def ripple_since
    created = ripples.last&.created_at&.to_time&.to_i
    today =  Time.now.to_time.to_i
    (today - created).ago.to_words if created && today
  end

  # For rails routing
  # Override id as default route param
  def to_param
    key
  end

  private

  def initialize_key
    self.key ||= "P-#{SecureRandom.hex(3).upcase}"
  end

  # Validation methods

  def validate_key
    return unless key

    errors.add(:key, 'must be a string') unless key.is_a?(String)
    errors.add(:key, 'must start with P-') unless key.first(2) == 'P-'
    errors.add(:key, 'must be 8 charcters long') unless key.size == 8
  end

  def uppercase_key
    self.key = key.upcase
  end
end

app/controllers/Api/Internal/ponds_controller.rb
# frozen_string_literal: true

module Api
  module Internal
    class PondsController < ::Api::BaseController
      before_action :find_pond, only: [:show]

      def index
        render json: Pond.all.includes([:ripples]), each_serializer: ::Internal::PondSerializer
      end

      def show
        render json: @pond, serializer: ::Internal::PondSerializer
      end

      private

      def find_pond
        @pond ||= Pond.find_by!(id: params[:id])
      end
    end
  end
end

app/controllers/ponds_controller.rb
# frozen_string_literal: true

class PondsController < ApplicationController
  before_action :set_pond, only: :show

  def index
    @pagy, @ponds = pagy(Pond.all.order(created_at: :desc))
  end

  def show
    @ripples = @pond.ripples
  end

  private

  def set_pond
    @pond = Pond.friendly.find_by!(key: params[:key].upcase)
  end
end

app/views/ponds/_form.html.haml
= form_for @pond do |f|
  - if @pond.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pond.errors.count, "error")} prohibited this pond from being saved:"
      %ul
        - @pond.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :uuid
    = f.text_field :uuid
  .field
    = f.label :postal_code
    = f.text_field :postal_code
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :region
    = f.text_field :region
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :key
    = f.text_field :key
  .actions
    = f.submit 'Save'

app/views/ponds/index.html.haml
.ripples-bg-color
- if @ponds&.count&.zero?
  .container.w-50.mt-5.py-5
    .container.text-center
      %h1{ style: 'color: #78b14f'} nothing to see here....
      %em.text-muted No ponds have been created yet but, when they are they will show up here.
    %div{:style => "width:100%;height:0;padding-bottom:75%;position:relative;"}
      %iframe.giphy-embed{:allowfullscreen => "", :frameborder => "0", :height => "100%", :src => "https://giphy.com/embed/a93jwI0wkWTQs", :style => "position:absolute", :width => "100%"}
      %p
        %a{:href => "https://giphy.com/gifs/dl-a93jwI0wkWTQs"} via GIPHY
- else
  .contianer.mt-5.text-center
    %h1{ style: 'color: #1484ac'}Ponds
    %em.text-muted A Pond represents a single act of KindCard. Each time a KindCard is created a new Pond is recorded.

  .container.my-5
    .row
      .col-lg-4.justify-content-center
        .my-4
          .row.px-3{ style: 'color: #edc06d'}
            %span.material-symbols-outlined.material-icons.pt-3{ style: 'font-size: 2em'} data_usage
            %h3.m-2 Quick Stats
          %hr 
          .row.px-3
            %p
              %strong Total Ponds:
              = Pond.count
          .row.px-3
            %p
              %strong The last Ripple of Kindness was:
              = Ripple.ripple_since
          .row.px-3
            %p
              %strong The last KindCard Release was:
              = Release.last.created_at.strftime('%B %d, %Y')
            -# Stat.recently_active_ponds(3)
      .col-lg-8.justify-content-center
        .flex
        - @ponds.each do |pond|
          = link_to pond_path(pond) do
            .card.my-4{style: 'width: 100%;'}
              %iframe.card-img-top{allowfullscreen: '', frameborder: '0', height: '540', src: "https://www.google.com/maps/embed/v1/place?key=#{EnvSecret.get('GOOGLE_MAPS_API_KEY')}&q=#{pond.full_location}", style: 'border:0', width: '100%', loading: 'lazy'}
              .card-body
                %p.my-4.pb-1.text-muted.card-text.text-center
                  = pond.full_location
                .row{ style: 'color: #1484ac'}
                  .col.text-center
                    %i.bi.bi-calendar3{ style: 'font-size: 2em'}
                    %p Created
                    %p= pond.created_at.strftime('%B %d, %Y')
                  .col.text-center
                    %i.bi.bi-droplet-fill{ style: 'font-size: 2em'}
                    %p Impact
                    %p= pond.impact
                  .col.text-center
                    %i.bi.bi-flag-fill{ style: 'font-size: 2em'}
                    %p Domestic Impact
                    %p= pond.domestic_impact
                  .col.text-center
                    %span.material-symbols-outlined.material-icons{ style: 'font-size: 2em'} public
                    %p International Impact
                    %p= pond.international_impact
    .container
      .row.justify-content-center
        .col-sm-1.text-center
          = raw pagy_bootstrap_nav(@pagy)

app/views/ponds/show.html.haml
.pond.m-5.p-2
  .container
    %h1.text-center= @pond.key
    %p.text-muted.text-center A pond represents a single KindCard. Each ripple in that pond is a record of an individual act of kindness and the KindCard being passed on.
    %hr/
    .row
      .col-sm-8
        %iframe{:allowfullscreen => "", :frameborder => "0", :height => "540", :src => "https://www.google.com/maps/embed/v1/place?key=#{EnvSecret.get('GOOGLE_MAPS_API_KEY')}&q=#{@pond.full_location}", :style => "border:0", :width => "100%"}
      #contact2.col-sm-4
        %h3 About This Pond
        %hr{:align => "left", :width => "50%"}/
        %h4.pt-2{ style: 'color: #1484ac' } Location
        - if @pond.postal_code
          %p
            %b Postal code:
            = @pond.postal_code
        - if @pond.city
          %p
            %b City:
            = @pond.city
        - if @pond.region.present?
          - if @pond.domestic?
            %p
              %b State:
              = @pond.state
          - else
            %p
              %b Region:
              = @pond.region
          
        - if @pond.country
          %p
            %b Country:
            = @pond.country
        %br/
        = link_to(pond_ripples_path(@pond)) do
          %h4.pt-2{ style: 'color: #1484ac' } Impact
        %p
          %b Domestic Impact:
          = @pond.domestic_impact
        %p
          %b International Impact:
          = @pond.international_impact
        %br/
        %h4.pt-2{ style: 'color: #1484ac' } Last Ripple Recorded
        %p
          %b= @pond.ripple_since
        %br/
        %h4.pt-2{ style: 'color: #1484ac' } Details
        %p
          %b Organization:
          = link_to @pond.organization.name, organization_path(@pond.organization)
        %p
          %b Release:
          = link_to @pond.release.name, organization_release_path(@pond.organization, @pond.release)
        %p
          %b ID:
          = @pond.uuid
        %p
          %b Created:
          = local_time_ago(@pond.created_at)
        %br/


- if @pond.ripples.present?
  %section.pt-5.pb-5
    .container
      .row
        .col-6
          %h3.mb-3 Ripples
        .col-6.text-right
          %a.btn.btn-primary.mb-3.mr-1{"data-slide" => "prev", :href => "#carouselExampleIndicators2", :role => "button"}
            %i.bi.bi-chevron-left
          %a.btn.btn-primary.mb-3{"data-slide" => "next", :href => "#carouselExampleIndicators2", :role => "button"}     
            %i.bi.bi-chevron-right
        .col-12
          #carouselExampleIndicators2.carousel.slide{"data-ride" => "carousel"}
            .carousel-inner
              - @pond.ripples.each_slice(3).to_a.each_with_index do |group, index|
                .carousel-item{ class: "#{ index == 0 ? 'active' : '' }"}
                  .row
                    - group.each do |ripple|
                      .col-md-4.mb-3.d-flex.align-items-stretch
                        .card
                          = image_tag('default_map.png', class: 'img-fluid', alt: 'map' )
                          .card-body
                            = link_to pond_ripple_path(@pond, ripple), class: 'ripple-pond-a' do
                              %h4.card-title= "#{ripple.city}, #{ripple.region}"
                              %p.card-text
                                %b Recorded:
                                = local_time_ago(ripple.created_at)