config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  unauthenticated do
    root 'pages#home'
  end 

  # Service Workers
  get '/manifest.json', to: 'service_workers/manifests#index'

  # Users
  devise_for :users, skip: [:registrations, :invitation]
  devise_scope :user do
    resource :users,
            only: [:edit, :update, :destroy],
            controller: 'devise/registrations',
            as: :user_registration do
      get 'cancel'
    end
  end

  devise_scope :user do
    get "/users/invitation/accept", to: "devise/invitations#edit",   as: 'accept_user_invitation'
    patch '/users/invitation', to: 'devise/invitations#update', as: 'user_invitation'
  end

  # Super Admin User
  authenticated :user, ->(u) { u.super_admin? } do
    # Sidekiq
    mount Sidekiq::Web => '/sidekiq'
    mount Flipper::UI.app(Flipper) => '/flipper'
    root 'manage/manage#dashboard', as: :manager_root

    devise_scope :user do
      get "/users/invitation/accept", to: "devise/invitations#edit",   as: 'manage_accept_user_invitation'
      get '/users/invitation/new', to: 'devise/invitations#new', as: 'manage_new_user_invitation'
      patch '/users/invitation', to: 'devise/invitations#update', as: 'manage_user_invitation'
      put "/users/invitation", to: "devise/invitations#update", as:  nil
    end

    # Manage
    namespace :manage do
      root 'manage#dashboard', as: :manager_root
      get '/ripples', to: 'manage#ripples', as: 'ripples'
      get '/releases', to: 'manage#releases', as: 'releases'
      get '/tags', to: 'manage#tags', as: 'tags'

      resources :ponds, param: :key do
        resources :ripples, param: :uuid
      end

      resources :tags, param: :name
      resources :stories, param: :uuid
      resources :orders, param: :uuid
      post '/orders/:uuid/send_message', to: 'orders#send_message', as: 'order_send_message'
      resources :bills
      resources :organizations, param: :name do 
        resources :releases do 
          resources :pond_batch_record, only: [:new, :create]
        end
        resources :tags, param: :name, only: [:index, :show]
      end
    end
  end

  # Admin User
  authenticated :user, ->(u) { u.admin? } do
    # Manage
    namespace :manage do
      resources :ponds, param: :key do
        resources :ripples, param: :uuid
      end

      resources :orders, param: :uuid
      resources :tags, param: :name
      resources :stories, param: :uuid
      resources :organizations, param: :name do 
        resources :releases
        resources :tags, param: :name, only: [:index, :show]
      end
    end
  end 

  # Pages
  get '/ripples', to: 'pages#ripples'
  get '/impact', to: 'pages#impact'
  get '/donate', to: 'pages#donate'
  get '/contribute', to: 'pages#contribute'
  get '/privacy', to: 'pages#privacy_policy'
  get '/terms', to: 'pages#terms'
  get '/thank-you', to: 'pages#thank_you'
  get '/explained', to: 'pages#explained'
  get '/gracehaven', to: 'pages#partner', as: 'partner'

  # Orders
  resources :orders, param: :uuid, only: %i[show new create]

  # Donations
  resources :donations, only: [:create]

  # Ponds and Ripples
  resources :ponds, param: :key, only: [:index, :show] do
    resources :ripples, param: :uuid, only: [:index, :show, :create, :new]
  end

  # Tags
  resources :tags, param: :name, only: [:index, :show, :new, :create]

  # Stories
  resources :stories, param: :uuid, only: [:new, :create]

  # Organizations
  resources :organizations, param: :name, only: [:index, :show] do 
    resources :releases, only: [:index, :show]
    resources :tags, param: :name, only: [:index, :show]
  end

  # Twilio Message Subscriptions
  post '/messagesubscriptions/sms', to: 'message_subscriptions#sms'

  # API Routes
  namespace :api do
    get '/_ping', to: 'health#ping'

    namespace :internal do
      resources :ponds, only: [:index, :show]
      resources :ripples, only: [:index, :show]
      resources :organizations, only: [:index, :show]
      resources :releases, only: [:index, :show]
      resources :tags, only: [:index, :show]
      resources :stories, only: [:index, :show]
      get '/impact', to: 'impact#show'
    end
  end
  

end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  extend FriendlyId
  # Schema Information
  # Table name: Tag
  #
  # id                  :integer      not null, primary key
  # name                :string       not null
  # approved            :boolean
  # description         :text         not null
  # organization        :string
  # deleted_at          :datetime
  # created_at          :datetime     not null
  # updated_at          :datetime     not null

  # Validations
  validate  :validate_tag_name
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :name, length: { in: 1..45 }
  validates :description, length: { in: 5..350 }

  # Associations
  belongs_to :organization
  has_and_belongs_to_many :ripples

  # Gem Configurations
  has_paper_trail
  acts_as_paranoid
  friendly_id :name, use: :slugged

  # Scopes
  scope :approved, -> { where({ approved: true }) }
  scope :pending_approval, -> { where({ approved: nil }) }
  scope :denied, -> { where({ approved: false }) }

  # Public Class Method
  # Return the most popular tag
  #
  def self.most_popular
    return unless RipplesTag.count.positive?

    tags_hash = joins(:ripples_tags).group(:tag_id).count
    tag_id = tags_hash.max_by { |_k, v| v }[0]
    find_by(id: tag_id)
  end

  def self.leaderboard
    includes(:organization)
      .joins(:ripples_tags)
      .group('tag_id', 'tags.id', 'tags.name')
      .order('COUNT(tags.id) DESC')
      .limit(5)
  end

  # For rails routing
  # Override id as default route param
  def to_param
    name
  end

  def approval
    return 'Pending' if approved.nil?
    return 'Denied' if approved.eql?(false)
    return 'Approved' if approved.eql?(true)
  end

  private

  def validate_tag_name
    return unless name

    errors.add(:name, 'must start with a #') unless name.first == '#'
    errors.add(:name, 'can not contain space') if name.include?(' ')
  end
end

app/controllers/Api/Internal/tags_controller.rb
# frozen_string_literal: true

module Api
  module Internal
    class TagsController < ::Api::BaseController
      before_action :find_tag, only: [:show]

      def index
        render json: Tag.approved.includes([:organization]),
               each_serializer: ::Internal::TagSerializer
      end

      def show
        render json: @tag, serializer: ::Internal::TagSerializer
      end

      private

      def find_tag
        @tag ||= Tag.find_by!(id: params[:id])
      end
    end
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  THE_POND_PROJECT = 'ThePondProject'

  before_action :set_tag, only: %i[show]

  def index
    @tags = Tag.approved
  end

  def show; end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    # Tags default to ThePondProject
    @tag.organization = Organization.find_by(name: THE_POND_PROJECT)

    if @tag.save
      msg = 'Tag was successfully submitted. Your tag will be reviewed and approved within 2 days.'

      redirect_to tags_url, notice: msg
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_tag
    @tag = Tag.friendly.find_by!(name: params[:name])
  end

  def tag_params
    params.require(:tag).permit(:name, :description, :approved)
  end
end

app/views/tags/_form.html.haml
= form_for @tag do |f|
  - if @tag.errors.any?
    .container
      #error_explanation
        %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
        %ul
          - @tag.errors.full_messages.each do |message|
            %li= message


  .form-group
    .container
      %hr
      .row.m-3 
        .col-md-4.col-md-6.pt-4
          = f.text_field :name, placeholder: '#yournewtag', class: 'form-control', required: true
        .col-md-4.col-md-6.pt-4
          = f.text_field :description, placeholder: 'A description for your tag', class: 'form-control', required: true
      .row.m-3
        .actions.m-3
          = f.submit 'Submit', class: 'btn btn-outline-primary'

app/views/tags/index.html.haml
.container.pt-4.d-flex.flex-sm-row.flex-column.align-items-center
  .svg-container.w-50
    = show_svg('hashtag.svg')
  .tags-jumbotron.mx-3
    %h1 Tags
    %p.tags-paragraph.text-muted.flex-fill
      Here are all the tags that can be used when recording a ripple. Don't see a tag you like? Add your own!
    = link_to 'Create a tag', new_tag_path, { class:'btn btn-primary'}

%hr
.container.mt-5.tags-show
  %ul.tags.mt-4
    - @tags.each do |tag|
      = link_to tag_path(tag) do  
        %li.mx-3
          %button.tag_style   
            = tag.name
            %span
              %p.tag_count
                = tag.ripples.count

.push-footer.mb-5

app/views/tags/new.html.haml
.container.mt-4
  %h2.px-4{ style: 'color: #1484ac '} Create a tag

= render 'form'

.push-footer.mb-5

app/views/tags/show.html.haml
.container.mt-5.tags-show
  %ul.tags.mt-4
    %li.mx-3
      %button.tag_style   
        = @tag.name
        %span
          %p.tag_count
            = @tag.ripples.count
  .mx-3
    %p.my-2
      %b Organization:
      = link_to @tag.organization.name, organization_path(@tag.organization)
      =  + ' |'
      %b Approval:
      = @tag.approval + ' |'
      %b Created:
      = local_time_ago(@tag.created_at)
    %p.text-muted.my-2
      = @tag.description
  %hr

- unless @tag.ripples.empty?
  %section.pt-5.pb-5
    .container
      .row
        .col-6
          %h3.mb-3 Ripples
        .col-6.text-right
          %a.btn.btn-primary.mb-3.mr-1{"data-slide" => "prev", :href => "#carouselExampleIndicators2", :role => "button"}
            %i.bi.bi-chevron-left
          %a.btn.btn-primary.mb-3{"data-slide" => "next", :href => "#carouselExampleIndicators2", :role => "button"}     
            %i.bi.bi-chevron-right
        .col-12
          #carouselExampleIndicators2.carousel.slide{"data-ride" => "carousel"}
            .carousel-inner
              - @tag.ripples.each_slice(3).to_a.each_with_index do |group, index|
                .carousel-item{ class: "#{ index == 0 ? 'active' : '' }"}
                  .row
                    - group.each do |ripple|
                      .col-md-4.mb-3.d-flex.align-items-stretch
                        .card
                          = image_tag('default_map.png', class: 'img-fluid', alt: 'map' )
                          .card-body
                            = link_to pond_ripple_path(ripple.pond, ripple.uuid) do
                              %h4.card-title= "#{ripple.city}, #{ripple.region}"
                            %p.card-text
                              %b Created:
                              = local_time_ago(ripple.created_at)

.push-footer.mb-5