config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  unauthenticated do
    root 'pages#home'
  end 

  # Service Workers
  get '/manifest.json', to: 'service_workers/manifests#index'

  # Users
  devise_for :users, skip: [:registrations, :invitation]
  devise_scope :user do
    resource :users,
            only: [:edit, :update, :destroy],
            controller: 'devise/registrations',
            as: :user_registration do
      get 'cancel'
    end
  end

  devise_scope :user do
    get "/users/invitation/accept", to: "devise/invitations#edit",   as: 'accept_user_invitation'
    patch '/users/invitation', to: 'devise/invitations#update', as: 'user_invitation'
  end

  # Super Admin User
  authenticated :user, ->(u) { u.super_admin? } do
    # Sidekiq
    mount Sidekiq::Web => '/sidekiq'
    mount Flipper::UI.app(Flipper) => '/flipper'
    root 'manage/manage#dashboard', as: :manager_root

    devise_scope :user do
      get "/users/invitation/accept", to: "devise/invitations#edit",   as: 'manage_accept_user_invitation'
      get '/users/invitation/new', to: 'devise/invitations#new', as: 'manage_new_user_invitation'
      patch '/users/invitation', to: 'devise/invitations#update', as: 'manage_user_invitation'
      put "/users/invitation", to: "devise/invitations#update", as:  nil
    end

    # Manage
    namespace :manage do
      root 'manage#dashboard', as: :manager_root
      get '/ripples', to: 'manage#ripples', as: 'ripples'
      get '/releases', to: 'manage#releases', as: 'releases'
      get '/tags', to: 'manage#tags', as: 'tags'

      resources :ponds, param: :key do
        resources :ripples, param: :uuid
      end

      resources :tags, param: :name
      resources :stories, param: :uuid
      resources :orders, param: :uuid
      post '/orders/:uuid/send_message', to: 'orders#send_message', as: 'order_send_message'
      resources :bills
      resources :organizations, param: :name do 
        resources :releases do 
          resources :pond_batch_record, only: [:new, :create]
        end
        resources :tags, param: :name, only: [:index, :show]
      end
    end
  end

  # Admin User
  authenticated :user, ->(u) { u.admin? } do
    # Manage
    namespace :manage do
      resources :ponds, param: :key do
        resources :ripples, param: :uuid
      end

      resources :orders, param: :uuid
      resources :tags, param: :name
      resources :stories, param: :uuid
      resources :organizations, param: :name do 
        resources :releases
        resources :tags, param: :name, only: [:index, :show]
      end
    end
  end 

  # Pages
  get '/ripples', to: 'pages#ripples'
  get '/impact', to: 'pages#impact'
  get '/donate', to: 'pages#donate'
  get '/contribute', to: 'pages#contribute'
  get '/privacy', to: 'pages#privacy_policy'
  get '/terms', to: 'pages#terms'
  get '/thank-you', to: 'pages#thank_you'
  get '/explained', to: 'pages#explained'
  get '/gracehaven', to: 'pages#partner', as: 'partner'

  # Orders
  resources :orders, param: :uuid, only: %i[show new create]

  # Donations
  resources :donations, only: [:create]

  # Ponds and Ripples
  resources :ponds, param: :key, only: [:index, :show] do
    resources :ripples, param: :uuid, only: [:index, :show, :create, :new]
  end

  # Tags
  resources :tags, param: :name, only: [:index, :show, :new, :create]

  # Stories
  resources :stories, param: :uuid, only: [:new, :create]

  # Organizations
  resources :organizations, param: :name, only: [:index, :show] do 
    resources :releases, only: [:index, :show]
    resources :tags, param: :name, only: [:index, :show]
  end

  # Twilio Message Subscriptions
  post '/messagesubscriptions/sms', to: 'message_subscriptions#sms'

  # API Routes
  namespace :api do
    get '/_ping', to: 'health#ping'

    namespace :internal do
      resources :ponds, only: [:index, :show]
      resources :ripples, only: [:index, :show]
      resources :organizations, only: [:index, :show]
      resources :releases, only: [:index, :show]
      resources :tags, only: [:index, :show]
      resources :stories, only: [:index, :show]
      get '/impact', to: 'impact#show'
    end
  end
  

end

app/views/layouts/partials/_alerts.html.haml
- if notice
  .alert.alert-success{:role => "alert"}
    = notice
- if alert
  .alert.alert-danger{:role => "alert"}
    = alert

app/views/layouts/partials/_footer.html.haml
-#  fixed-bottom
%footer#footer
  .container
    .row
      .col-md-4.footer-column
        %ul.nav.flex-column
          %li.nav-item
            %span.footer-title Impact
          - if Flipper.enabled?(:accepting_partners)
            %li.nav-item
              = link_to 'Organizations', organizations_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Tags', tags_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Ponds', ponds_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Ripples', ripples_path, class: 'nav-link'
      .col-md-4.footer-column
        %ul.nav.flex-column
          %li.nav-item
            %span.footer-title Get Involved
          %li.nav-item
            = link_to 'Donate', donate_path, class: 'nav-link'
          %li.nav-item
            %a.nav-link{href: "https://github.com/The-Pond-Project/samaritan"} Contribute
          %li.nav-item
            %a.nav-link{:href => "https://www.gracehaven.me/"} Gracehaven
      .col-md-4.footer-column
        %ul.nav.flex-column
          %li.nav-item
            %span.footer-title Connect
          %li.nav-item
            = link_to 'Story of Kindness', new_story_path, class: 'nav-link'
          %li.nav-item
            = mail_to "kindnesspassedon@gmail.com", 'Email'
    .text-center
      %i.fas.fa-ellipsis-h
    .row.text-center
      .col-md-4.box
        %span.copyright.quick-links
          ThePondProject 2022
      .col-md-4.box
        %ul.list-inline.social-buttons
          %li.list-inline-item
            %a{href: 'https://www.instagram.com/kindnesspassedon/'}
              %i.bi.bi-instagram
          %li.list-inline-item
            %a{href: 'https://www.linkedin.com/company/thepondproject/'}
              %i.bi.bi-linkedin
          %li.list-inline-item
            %a{href: 'https://twitter.com/thepondproject'}
              %i.bi.bi-twitter
          %li.list-inline-item
            %a{:href => 'https://www.facebook.com/The-Pond-Project-102601682554651'}
              %i.bi.bi-facebook
      .col-md-4.box
        %ul.list-inline.quick-links
          %li.list-inline-item
            = link_to 'Privacy Policy', privacy_path
          %li.list-inline-item
            = link_to 'Terms of Use', terms_path

app/views/layouts/partials/_manage_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.shadow-sm.fixed-top.bg-navbar
  = link_to image_tag('thepondproject.png', style: ' height: 30px'), manager_root_path, class: 'navbar-brand d-flex align-items-center'
  %button.navbar-toggler.navbar-toggler-right.border-0{"data-target" => "#navbar4", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbar4.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto.mt-3.mt-lg-0
      %li.nav-item.px-lg-2
        = link_to 'Impact', impact_path, class: 'nav-link'
        %span.d-inline-block.d-lg-none.icon-width>
          %i.far.fa-user
      %li.nav-item.px-lg-2
        = link_to 'Ponds', manage_ponds_path, class: 'nav-link'
      %li.nav-item.px-lg-2
        = link_to 'Organizations', manage_organizations_path, class: 'nav-link'
        %span.d-inline-block.d-lg-none.icon-width>
          %i.far.fa-user
      %li.nav-item.px-lg-2
        = link_to 'Releases', manage_releases_path, class: 'nav-link'
        %span.d-inline-block.d-lg-none.icon-width>
          %i.far.fa-user
      %li.nav-item.px-lg-2
        = link_to 'Bills', manage_bills_path, class: 'nav-link'
        %span.d-inline-block.d-lg-none.icon-width>
          %i.far.fa-user
      %li.nav-item.px-lg-2
        = link_to 'Tags', manage_tags_path, class: 'nav-link'
        %span.d-inline-block.d-lg-none.icon-width>
          %i.far.fa-user
      %li.nav-item.px-lg-2
        = link_to 'Orders', manage_orders_path, class: 'nav-link'
        %span.d-inline-block.d-lg-none.icon-width>
          %i.far.fa-user
      %li.nav-item.px-lg-2
        = link_to 'Flipper', '/flipper/features', class: 'nav-link'
        %span.d-inline-block.d-lg-none.icon-width>
          %i.far.fa-user
      %li.nav-item.px-lg-2
        = link_to 'Sidekiq', '/sidekiq', class: 'nav-link'
        %span.d-inline-block.d-lg-none.icon-width>
          %i.far.fa-user
    %ul.navbar-nav.ml-auto.mt-3.mt-lg-0
      - if user_signed_in?
        %li.nav-item.px-lg-2
          = link_to 'Edit Account', edit_user_registration_path 
          %span.d-inline-block.d-lg-none.icon-width>
            %i.far.fa-user
        %li.nav-item.px-lg-2
          = link_to 'Logout', destroy_user_session_path, method: :delete
          %span.d-inline-block.d-lg-none.icon-width>
            %i.far.fa-user
      - else
        %li.nav-item.px-lg-2
          = link_to 'Login', new_user_session_path
          %span.d-inline-block.d-lg-none.icon-width>
            %i.far.fa-user

app/views/layouts/partials/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.shadow-sm.fixed-top.bg-navbar
  = link_to image_tag('thepondproject.png', style: ' height: 30px', alt: 'The Pond Project logo'), root_path, class: 'navbar-brand d-flex align-items-center'
  %button.navbar-toggler.navbar-toggler-right.border-0{"data-target" => "#navbar4", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbar4.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto.mt-3.mt-lg-0
      %li.nav-item.px-lg-2
        = link_to 'Impact', impact_path, class: 'nav-link'
      %li.nav-item.px-lg-2
        = link_to 'Ponds', ponds_path, class: 'nav-link'
      %li.nav-item.px-lg-2
        = link_to 'Ripples', ripples_path, class: 'nav-link'
      - if Flipper.enabled?(:accepting_partners)
        %li.nav-item.px-lg-2
          = link_to 'Partners', organizations_path, class: 'nav-link'
      %li.nav-item.px-lg-2
        = link_to 'Gracehaven', partner_path, class: 'nav-link'
      - if Flipper.enabled?(:pond_project_donations)
        %li.nav-item.px-lg-2
          = link_to 'Donate', donate_path, class: 'nav-link'
      - else
        %li.nav-item.px-lg-2
          = link_to 'Tags', tags_path, class: 'nav-link'
      - if Flipper.enabled?(:kindcard_orderable)
        %li.nav-item.px-lg-2
          = link_to 'Order KindCards', new_order_path, class: 'nav-link'
      %li.nav-item.px-lg-2.dropdown.d-menu
        %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded": "false", "aria-haspopup": "true", "data-toggle": "dropdown", :href => "#"}
          %span.d-inline-block.d-lg-none.icon-width>
            %i.far.fa-caret-square-down
          More
        .dropdown-menu.shadow-sm.sm-menu{"aria-labelledby" => "dropdown01"}
          = link_to 'Contribute', contribute_path, class: 'dropdown-item'
          - if Flipper.enabled?(:pond_project_donations)
            = link_to 'Tags', tags_path, class: 'dropdown-item'
    %ul.navbar-nav.ml-auto.mt-3.mt-lg-0
      - if user_signed_in?
        %li.nav-item.px-lg-2
          = link_to 'Edit Account', edit_user_registration_path 
          %span.d-inline-block.d-lg-none.icon-width>
            %i.far.fa-user
        %li.nav-item.px-lg-2
          = link_to 'Logout', destroy_user_session_path, method: :delete
          %span.d-inline-block.d-lg-none.icon-width>
            %i.far.fa-user
      - else
        %li.nav-item.px-lg-2
          = link_to 'Login', new_user_session_path
          %span.d-inline-block.d-lg-none.icon-width>
            %i.far.fa-user